### ISSUE TITLE
> php artisan clear-compiled while installation 

### ISSUE THREAD

**Issue by a1iraxa** [mikimaine/ecommerce#11]
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Mikimaine\Demo\DemoServiceProvider' not found

PHP Fatal error:  Class 'Mikimaine\Demo\DemoServiceProvider' not found in <path_to_directory>\ecommerce-test\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 146
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255

**Comment by mikimaine** [comment]
hey a1iraxa, after what command does this error shows?

**Comment by mikimaine** [comment]
And you can ignore that error for now until i solve it , you can continue to the next step it will not affect it .
i will clean it up soon! thanks for info!

**Comment by a1iraxa** [comment]
While creating new project using this command.
**composer create-project mikimaine/ecommerce yourprojectname**

**Comment by a1iraxa** [comment]
Due to this error installation does not complete.

**Comment by mikimaine** [comment]
For some reason  composer create-project mikimaine/ecommerce yourprojectname  command is not downloading the latest commit . until i figure this out you can fix the error 
1 - open composer.json and remove 
   `"Mikimaine\\Demo\\": "packages/Mikimaine/Demo/src/"`  in line 57
2- open the file config/app.php and remove 
   `Mikimaine\Demo\DemoServiceProvider::class,` in line 196 and 
   `'Demo' => Mikimaine\Demo\DemoFacade::class,` in line 268
That should do the trick for no but i will fix this soon.

**Comment by mikimaine** [comment]
and your install is late so you can download the latest zip and replace for now.
The latest zip is here -->    https://github.com/mikimaine/ecommerce/archive/0.1.1.zip     
so download and replace the content by this .

**Comment by MCON** [comment]
used contents of your zip:
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Class 'Intervention\Image\ImageServiceProvider' not found

**Comment by mikimaine** [comment]
im trying to recreate this error , is this on installation ??
have u run the `composer install` and then `composer dumpautoload`

**Comment by mikimaine** [comment]
and also run this command `composer require intervention/image`

**Comment by mikimaine** [comment]
Hey i have fixed this error and release a new version ..... 
please try again with the download and install the new verion is 0.1.5 so download that again .

Everything is working now. please follow the installation in the read me file.

Thanks!

**Comment by a1iraxa** [comment]
Okay thanks man. : )
