### ISSUE TITLE
Nothing to migrate.

### ISSUE THREAD

**Issue by SaidiYusof** [mikimaine/ecommerce#19]
![nothing to migrate](https://cloud.githubusercontent.com/assets/19275984/24594912/2fe718de-1864-11e7-88c8-c5885eb6ed4f.png)

**Comment by mikimaine** [comment]
One last information did you use `composer create project mikimaine/ecommerce` or git clone ?

**Comment by mikimaine** [comment]
please can you check you database if there is table  created ?
