### ISSUE TITLE
I follow the install steps, and I encounter a problem when I enter "php innovate key:generate"

### ISSUE THREAD

**Issue by timloo0710** [mikimaine/ecommerce#21]
The message as following:

PHP Warning:  require(/home/timloo/composer_php/eshop/innovEshop/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/timloo/composer_php/eshop/innovEshop/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /home/timloo/composer_php/eshop/innovEshop/innovate:0
PHP   2. require() /home/timloo/composer_php/eshop/innovEshop/innovate:16
PHP Fatal error:  require(): Failed opening required '/home/timloo/composer_php/eshop/innovEshop/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/timloo/composer_php/eshop/innovEshop/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /home/timloo/composer_php/eshop/innovEshop/innovate:0
PHP   2. require() /home/timloo/composer_php/eshop/innovEshop/innovate:16

I found that there is not autoload.php inside the vendor folder.

Thanks for any comments.

**Comment by mikimaine** [comment]
you should first install the packages. 

run `composer install `

**Comment by timloo0710** [comment]
When I ran composer install, it shows

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package spatie/activitylog is abandoned, you should avoid using it. Use spatie/laravel-activitylog instead.
Package league/url is abandoned, you should avoid using it. Use league/uri instead.
Generating autoload files

                                                                               
  [RuntimeException]                                                           
  Could not scan for classes inside "tests/Testcase.php" which does not appea  
  r to be a file nor a folder                                                  
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

------------------------------------------------
How can I solve this?? Thanks

**Comment by mikimaine** [comment]
Yes you are correct until I draft a new release, go to composer file and remove 
`"tests/Testcase.php"` from line 67 the run the command `composer dumpautoload` 
I am currently rewriting the whole project in Laravel5.4 and VUEjs 2. 
 `

**Comment by mikimaine** [comment]
the current release solves this problem. If you don't want to edit the composer.json file. 
Please create the project from scratch and the new release should solve it by now.
