### ISSUE TITLE
Rewite using Laravel 5.4 and VUE.js 

### ISSUE THREAD

**Issue by mikimaine** [mikimaine/ecommerce#22]
I'm going to rewrite the whole application with Laravel 5.4 and VUEjs. 

If you have any feature request , send it to me.

**Comment by mikimaine** [comment]
- [ ] In the process of re-writing this project, we are going to minimize the uses of third party packages, less dependency. 

- [ ] Make the project TDD. All tests should be implemented correctly. 

- [ ] The frontend should be SPA (Single page application) [Vuejs or Reactjs] .

**Comment by adtsegaye** [comment]
Miki laravel 5.5 LTS is comming on July so it will be better to use so, you can play around with it with 5.4 but for this future app i think LTS will be favorable so as to remove future upgrading hassles.

**Comment by mikimaine** [comment]
@adtsegaye you are correct I was thinking about that also and I am actively following the changes happing to Laravel 5.5. I will be doing the System design (Including API ), Frontend Design(with Vue or React) and feature analysis (Choosing new features and removing unwanted ones).

**Comment by adtsegaye** [comment]
great keep going bro.

**Comment by mikimaine** [comment]
@adtsegaye and also 5.5 may not be LTS. Check this out:
https://twitter.com/taylorotwell/status/809768330118758400
So it will be win-win if we start development.

**Comment by mikimaine** [comment]
Already started a new branch using 5.5 today.
