### ISSUE TITLE
Databse Seed Not Working ?

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [mikimaine/ecommerce#23]
$ php innovate db:seed
INNOVATE E-COMMERCE CONSOLE  V0.1

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the man
  ual that corresponds to your MariaDB server version for the right syntax to use near 'CASCADE' at line 1 (S
  QL: TRUNCATE TABLE users CASCADE)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the man
  ual that corresponds to your MariaDB server version for the right syntax to use near 'CASCADE' at line 1

**Comment by mikimaine** [comment]
What type Db are you using?

**Comment by igorpdasilvaa** [comment]
the database is mariadb, same problem here.

**Comment by mikimaine** [comment]
will be solved with the next version.
