### ISSUE TITLE
When i register i says ?

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [mikimaine/ecommerce#24]
Whoops, looks like something went wrong.

1/1
Swift_TransportException in AbstractSmtpTransport.php line 162:
Cannot send message without a sender address

but credentials stored in database

**Comment by mikimaine** [comment]
That is because you haven't set an email appropriately in .env . 
set MAIL_DRIVER =file.

**Comment by mikimaine** [comment]
Will be solved with the next version.
