### ISSUE TITLE
Error Permission denied .when trying to install

### ISSUE THREAD

**Issue by mikihirpo** [mikimaine/ecommerce#3]
![capture](https://cloud.githubusercontent.com/assets/16518581/15098933/3d1323b4-14fe-11e6-8f83-2af0ca214e31.JPG)

**Comment by mikimaine** [comment]
Run cud as administrator and change the directory to xamp hydrocarbon folder .that will fix the error !

**Comment by mikimaine** [comment]
Will be solved using the new version.
